# This file is a CI/CD Configuration file for the project. This has been adapted from the sample file

image: maven:3.8-openjdk-21

stages:          # List of stages for jobs, and their order of execution
  - test
  - build


build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the code..."
    - ./mvnw clean compile
    - echo "Compile complete."

test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running tests..."
    - ./mvnw clean test
    - echo "Finished running tests."

